name: deepspain
channels:
  - defaults
dependencies:
  - pip:
      - click
      - aiohttp
      - black
      - dvc
      - boto3
      - tensorflow
      - tensorboardX
      - elasticsearch==7.0.4
      - fastai==1.0.57
      - torch==1.2.0
      - torchvision==0.4.0
